name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    env:
      SPONSORKIT_AFDIAN_USER_ID: ${{ secrets.AFDIAN_ID }}
      SPONSORKIT_AFDIAN_TOKEN: ${{ secrets.AFDIAN_TOKEN }}
      SPONSORKIT_AFDIAN_EXECHANGERATE: 1
    steps:
      - uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
          # node-version: 20.x
          cache: yarn

      - run: |
          npm i yarn -g
          yarn

      - name: Build Sponsorkit
        run: yarn build
        
      - name: Run Sponsorkit script
        run: node ./dist/cli.cjs

      - name: Upload
        uses: Teahouse-Studios/aliyun-oss-action@0.7
        with:
          KEY_ID: ${{ secrets.KEY_ID }}
          KEY_SECRET: ${{ secrets.KEY_SECRET }}
          BUCKET: frontend-wdljt
          LOCAL_PATH: ./sponsorkit/
          REMOTE_PREFIX: meme/sponsors_test/